name: Build and Push Docker Image

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Calculate next tag
              id: next-tag
              run: |
                  TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                  TAG="${TAG%.*}.$((${TAG##*.}+1))"
                  echo "::set-output name=tag::$TAG"
              shell: bash

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-repo:${{ steps.next-tag.outputs.tag }}
